apiVersion: virtualenvironmentclusterfirewallsecuritygroup.crossplane.io/v1alpha1
kind: EnvironmentClusterFirewallSecurityGroup
metadata:
  name: webserver-firewall-group
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: default
  forProvider:
    name: webserver
    comment: Managed by Crossplane

    rule:
      - type: in
        action: ACCEPT
        comment: Allow HTTP
        dest: 192.168.1.5
        dport: "80"
        proto: tcp
        log: info

      - type: in
        action: ACCEPT
        comment: Allow HTTPS
        dest: 192.168.1.5
        dport: "443"
        proto: tcp
        log: info
