apiVersion: virtualenvironmentaptrepository.crossplane.io/v1alpha1
kind: EnvironmentAptRepository
metadata:
  name: test-apt-repo
spec:
  providerConfigRef:
    name: default
  forProvider:
    enabled: true
    filePath: "/etc/apt/sources.list"
    index: 0
    node: pve
