apiVersion: virtualenvironmentfirewallalias.crossplane.io/v1alpha1
kind: EnvironmentFirewallAlias
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmentfirewallalias/v1alpha1/environmentfirewallalias
  labels:
    testing.upbound.io/example-name: local_network
  name: local-network
spec:
  forProvider:
    cidr: 192.168.0.0/23
    comment: Managed by Terraform
    name: local_network
    nodeName: ${proxmox_virtual_environment_vm.example.node_name}
    vmId: ${proxmox_virtual_environment_vm.example.vm_id}
