frontend:
  - changed-files:
      - any-glob-to-any-file: ['frontend/**']

backend:
  - changed-files:
      - any-glob-to-any-file: ['backend/**']

infra:
  - changed-files:
      - any-glob-to-any-file: ['infrastructure/**']

docs:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md']
