apiVersion: virtualenvironmentfirewalloptions.crossplane.io/v1alpha1
kind: EnvironmentFirewallOptions
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmentfirewalloptions/v1alpha1/environmentfirewalloptions
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dhcp: true
    enabled: false
    inputPolicy: ACCEPT
    ipfilter: true
    logLevelIn: info
    logLevelOut: info
    macfilter: false
    ndp: true
    nodeName: ${proxmox_virtual_environment_vm.example.node_name}
    outputPolicy: ACCEPT
    radv: true
    vmId: ${proxmox_virtual_environment_vm.example.vm_id}
