apiVersion: virtualenvironmentfile.crossplane.io/v1alpha1
kind: EnvironmentFile
metadata:
  name: cloud-config-snippet
providerConfigRef:
  name: default
spec:
  forProvider:
    contentType: "snippets"
    datastoreId: "local"
    nodeName: "pve"
    sourceRaw:
    - data: |
        #cloud-config
        chpasswd:
          list: |
            ubuntu:example
          expire: false
        hostname: example-hostname
        packages:
          - qemu-guest-agent
      fileName: "example.cloud-config.yaml"
