apiVersion: virtualenvironmentdownloadfile.crossplane.io/v1alpha1
kind: EnvironmentDownloadFile
metadata:
  name: debian-12-bookworm-iso
  annotations:
    crossplane.io/external-name: debian-12-generic-amd64-20231228-1609.img
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  forProvider:
    contentType: "iso"
    datastoreId: "local"
    nodeName: "pve"
    url: "https://cloud.debian.org/images/cloud/bookworm/20231228-1609/debian-12-generic-amd64-20231228-1609.qcow2"
    fileName: "debian-12-generic-amd64-20231228-1609.img"
    checksum: "d2fbcf11fb28795842e91364d8c7b69f1870db09ff299eb94e4fbbfa510eb78d141e74c1f4bf6dfa0b7e33d0c3b66e6751886feadb4e9916f778bab1776bdf1b"
    checksumAlgorithm: "sha512"
    overwrite: false
    uploadTimeout: 600
    verify: true
