apiVersion: virtualenvironmentfirewalloptions.crossplane.io/v1alpha1
kind: EnvironmentFirewallOptions
metadata:
  name: example-firewall-options
spec:
  providerConfigRef:
    name: default
  forProvider:
    nodeName: pve
    vmId: 100
    dhcp: true
    enabled: false
    ipfilter: false
    logLevelIn: info
    logLevelOut: info
    macfilter: false
    ndp: true
    inputPolicy: ACCEPT
    outputPolicy: ACCEPT
    radv: true