apiVersion: virtualenvironmentaptstandardrepository.crossplane.io/v1alpha1
kind: EnvironmentAptStandardRepository
metadata:
  name: apt-repo-no-subscription
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  forProvider:
    handle: no-subscription
    node: pve
