apiVersion: virtualenvironmenthosts.crossplane.io/v1alpha1
kind: EnvironmentHosts
metadata:
  name: first-node-host-entries
spec:
  forProvider:
    nodeName: pve
    entry:
      - address: 127.0.0.1
        hostnames:
          - localhost
          - localhost.localdomain
  providerConfigRef:
    name: default