apiVersion: virtualenvironmentfirewallrules.crossplane.io/v1alpha1
kind: EnvironmentFirewallRules
metadata:
  name: example-firewall-rules
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: default
  forProvider:
    nodeName: pve
    vmId: 100
    rule:
      - type: in
        action: ACCEPT
        comment: Allow HTTP
        dest: 192.168.1.5
        dport: "80"
        proto: tcp
        log: info
        enabled: true
      - type: in
        action: ACCEPT
        comment: Allow HTTPS
        dest: 192.168.1.5
        dport: "443"
        proto: tcp
        log: info
        enabled: true
      - iface: net0
        comment: From security group
        securityGroup: webserver-secgroup 
        enabled: true
