apiVersion: virtualenvironmenthosts.crossplane.io/v1alpha1
kind: EnvironmentHosts
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmenthosts/v1alpha1/environmenthosts
  labels:
    testing.upbound.io/example-name: first_node_host_entries
  name: first-node-host-entries
spec:
  forProvider:
    entry:
    - address: 127.0.0.1
      hostnames:
      - localhost
      - localhost.localdomain
    nodeName: first-node
