apiVersion: virtualenvironmentacmeaccount.crossplane.io/v1alpha1
kind: EnvironmentAcmeAccount
metadata:
  name: acme-account-example
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  forProvider:
    name: example
    contact: "example@email.com"
    directory: "https://acme-staging-v02.api.letsencrypt.org/directory"
    tos: "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf"