apiVersion: virtualenvironmentcontainer.crossplane.io/v1alpha1
kind: EnvironmentContainer
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmentcontainer/v1alpha1/environmentcontainer
  labels:
    testing.upbound.io/example-name: ubuntu_container
  name: ubuntu-container
spec:
  forProvider:
    description: Managed by Terraform
    disk:
    - datastoreId: local-lvm
      size: 4
    initialization:
    - hostname: terraform-provider-proxmox-ubuntu-container
      ipConfig:
      - ipv4:
        - address: dhcp
      userAccount:
      - keys:
        - ${trimspace(tls_private_key.ubuntu_container_key.public_key_openssh)}
        passwordSecretRef:
          key: attribute.result
          name: example-password
          namespace: upbound-system
    mountPoint:
    - path: /mnt/shared
      volume: /mnt/bindmounts/shared
    - path: /mnt/volume
      size: 10G
      volume: local-lvm
    networkInterface:
    - name: veth0
    nodeName: first-node
    operatingSystem:
    - templateFileId: ${proxmox_virtual_environment_download_file.latest_ubuntu_22_jammy_lxc_img.id}
      type: ubuntu
    startup:
    - downDelay: "60"
      order: "3"
      upDelay: "60"
    vmId: 1234

---

apiVersion: virtualenvironmentdownloadfile.crossplane.io/v1alpha1
kind: EnvironmentDownloadFile
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmentcontainer/v1alpha1/environmentcontainer
  labels:
    testing.upbound.io/example-name: latest_ubuntu_22_jammy_lxc_img
  name: latest-ubuntu-22-jammy-lxc-img
spec:
  forProvider:
    contentType: vztmpl
    datastoreId: local
    nodeName: first-node
    url: http://download.proxmox.com/images/system/ubuntu-20.04-standard_20.04-1_amd64.tar.gz
