//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentFile) DeepCopyInto(out *EnvironmentFile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentFile.
func (in *EnvironmentFile) DeepCopy() *EnvironmentFile {
	if in == nil {
		return nil
	}
	out := new(EnvironmentFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentFile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentFileInitParameters) DeepCopyInto(out *EnvironmentFileInitParameters) {
	*out = *in
	if in.ContentType != nil {
		in, out := &in.ContentType, &out.ContentType
		*out = new(string)
		**out = **in
	}
	if in.DatastoreID != nil {
		in, out := &in.DatastoreID, &out.DatastoreID
		*out = new(string)
		**out = **in
	}
	if in.FileMode != nil {
		in, out := &in.FileMode, &out.FileMode
		*out = new(string)
		**out = **in
	}
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.Overwrite != nil {
		in, out := &in.Overwrite, &out.Overwrite
		*out = new(bool)
		**out = **in
	}
	if in.SourceFile != nil {
		in, out := &in.SourceFile, &out.SourceFile
		*out = make([]SourceFileInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SourceRaw != nil {
		in, out := &in.SourceRaw, &out.SourceRaw
		*out = make([]SourceRawInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TimeoutUpload != nil {
		in, out := &in.TimeoutUpload, &out.TimeoutUpload
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentFileInitParameters.
func (in *EnvironmentFileInitParameters) DeepCopy() *EnvironmentFileInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentFileInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentFileList) DeepCopyInto(out *EnvironmentFileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnvironmentFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentFileList.
func (in *EnvironmentFileList) DeepCopy() *EnvironmentFileList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentFileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentFileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentFileObservation) DeepCopyInto(out *EnvironmentFileObservation) {
	*out = *in
	if in.ContentType != nil {
		in, out := &in.ContentType, &out.ContentType
		*out = new(string)
		**out = **in
	}
	if in.DatastoreID != nil {
		in, out := &in.DatastoreID, &out.DatastoreID
		*out = new(string)
		**out = **in
	}
	if in.FileMode != nil {
		in, out := &in.FileMode, &out.FileMode
		*out = new(string)
		**out = **in
	}
	if in.FileModificationDate != nil {
		in, out := &in.FileModificationDate, &out.FileModificationDate
		*out = new(string)
		**out = **in
	}
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.FileSize != nil {
		in, out := &in.FileSize, &out.FileSize
		*out = new(float64)
		**out = **in
	}
	if in.FileTag != nil {
		in, out := &in.FileTag, &out.FileTag
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.Overwrite != nil {
		in, out := &in.Overwrite, &out.Overwrite
		*out = new(bool)
		**out = **in
	}
	if in.SourceFile != nil {
		in, out := &in.SourceFile, &out.SourceFile
		*out = make([]SourceFileObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SourceRaw != nil {
		in, out := &in.SourceRaw, &out.SourceRaw
		*out = make([]SourceRawObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TimeoutUpload != nil {
		in, out := &in.TimeoutUpload, &out.TimeoutUpload
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentFileObservation.
func (in *EnvironmentFileObservation) DeepCopy() *EnvironmentFileObservation {
	if in == nil {
		return nil
	}
	out := new(EnvironmentFileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentFileParameters) DeepCopyInto(out *EnvironmentFileParameters) {
	*out = *in
	if in.ContentType != nil {
		in, out := &in.ContentType, &out.ContentType
		*out = new(string)
		**out = **in
	}
	if in.DatastoreID != nil {
		in, out := &in.DatastoreID, &out.DatastoreID
		*out = new(string)
		**out = **in
	}
	if in.FileMode != nil {
		in, out := &in.FileMode, &out.FileMode
		*out = new(string)
		**out = **in
	}
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.Overwrite != nil {
		in, out := &in.Overwrite, &out.Overwrite
		*out = new(bool)
		**out = **in
	}
	if in.SourceFile != nil {
		in, out := &in.SourceFile, &out.SourceFile
		*out = make([]SourceFileParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SourceRaw != nil {
		in, out := &in.SourceRaw, &out.SourceRaw
		*out = make([]SourceRawParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TimeoutUpload != nil {
		in, out := &in.TimeoutUpload, &out.TimeoutUpload
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentFileParameters.
func (in *EnvironmentFileParameters) DeepCopy() *EnvironmentFileParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentFileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentFileSpec) DeepCopyInto(out *EnvironmentFileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentFileSpec.
func (in *EnvironmentFileSpec) DeepCopy() *EnvironmentFileSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentFileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentFileStatus) DeepCopyInto(out *EnvironmentFileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentFileStatus.
func (in *EnvironmentFileStatus) DeepCopy() *EnvironmentFileStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentFileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceFileInitParameters) DeepCopyInto(out *SourceFileInitParameters) {
	*out = *in
	if in.Changed != nil {
		in, out := &in.Changed, &out.Changed
		*out = new(bool)
		**out = **in
	}
	if in.Checksum != nil {
		in, out := &in.Checksum, &out.Checksum
		*out = new(string)
		**out = **in
	}
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.MinTLS != nil {
		in, out := &in.MinTLS, &out.MinTLS
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceFileInitParameters.
func (in *SourceFileInitParameters) DeepCopy() *SourceFileInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourceFileInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceFileObservation) DeepCopyInto(out *SourceFileObservation) {
	*out = *in
	if in.Changed != nil {
		in, out := &in.Changed, &out.Changed
		*out = new(bool)
		**out = **in
	}
	if in.Checksum != nil {
		in, out := &in.Checksum, &out.Checksum
		*out = new(string)
		**out = **in
	}
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.MinTLS != nil {
		in, out := &in.MinTLS, &out.MinTLS
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceFileObservation.
func (in *SourceFileObservation) DeepCopy() *SourceFileObservation {
	if in == nil {
		return nil
	}
	out := new(SourceFileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceFileParameters) DeepCopyInto(out *SourceFileParameters) {
	*out = *in
	if in.Changed != nil {
		in, out := &in.Changed, &out.Changed
		*out = new(bool)
		**out = **in
	}
	if in.Checksum != nil {
		in, out := &in.Checksum, &out.Checksum
		*out = new(string)
		**out = **in
	}
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.MinTLS != nil {
		in, out := &in.MinTLS, &out.MinTLS
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceFileParameters.
func (in *SourceFileParameters) DeepCopy() *SourceFileParameters {
	if in == nil {
		return nil
	}
	out := new(SourceFileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRawInitParameters) DeepCopyInto(out *SourceRawInitParameters) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(string)
		**out = **in
	}
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.Resize != nil {
		in, out := &in.Resize, &out.Resize
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRawInitParameters.
func (in *SourceRawInitParameters) DeepCopy() *SourceRawInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourceRawInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRawObservation) DeepCopyInto(out *SourceRawObservation) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(string)
		**out = **in
	}
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.Resize != nil {
		in, out := &in.Resize, &out.Resize
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRawObservation.
func (in *SourceRawObservation) DeepCopy() *SourceRawObservation {
	if in == nil {
		return nil
	}
	out := new(SourceRawObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRawParameters) DeepCopyInto(out *SourceRawParameters) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(string)
		**out = **in
	}
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.Resize != nil {
		in, out := &in.Resize, &out.Resize
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRawParameters.
func (in *SourceRawParameters) DeepCopy() *SourceRawParameters {
	if in == nil {
		return nil
	}
	out := new(SourceRawParameters)
	in.DeepCopyInto(out)
	return out
}
