apiVersion: virtualenvironmentmetricsserver.crossplane.io/v1alpha1
kind: EnvironmentMetricsServer
metadata:
  name: example-influxdb-server
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: default
  forProvider:
    name: example_influxdb_server
    server: 192.168.3.2
    port: 8089
    type: influxdb
    influxDbProto: udp                 
    influxBucket: crossplane_metrics  
    influxOrganization: crossplane-lab  
    influxMaxBodySize: 25000000    
    timeout: 1    
    mtu: 1500  
