apiVersion: virtualenvironmentfirewallrules.crossplane.io/v1alpha1
kind: EnvironmentFirewallRules
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmentfirewallrules/v1alpha1/environmentfirewallrules
  labels:
    testing.upbound.io/example-name: inbound
  name: inbound
spec:
  forProvider:
    nodeName: ${proxmox_virtual_environment_vm.example.node_name}
    rule:
    - action: ACCEPT
      comment: Allow HTTP
      dest: 192.168.1.5
      dport: "80"
      log: info
      proto: tcp
      type: in
    - action: ACCEPT
      comment: Allow HTTPS
      dest: 192.168.1.5
      dport: "443"
      log: info
      proto: tcp
      type: in
    - comment: From security group
      iface: net0
      securityGroup: webserver
    vmId: ${proxmox_virtual_environment_vm.example.vm_id}
