apiVersion: virtualenvironmentclusterfirewallsecuritygroup.crossplane.io/v1alpha1
kind: EnvironmentClusterFirewallSecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmentclusterfirewallsecuritygroup/v1alpha1/environmentclusterfirewallsecuritygroup
  labels:
    testing.upbound.io/example-name: webserver
  name: webserver
spec:
  forProvider:
    comment: Managed by Terraform
    name: webserver
    rule:
    - action: ACCEPT
      comment: Allow HTTP
      dest: 192.168.1.5
      dport: "80"
      log: info
      proto: tcp
      type: in
    - action: ACCEPT
      comment: Allow HTTPS
      dest: 192.168.1.5
      dport: "443"
      log: info
      proto: tcp
      type: in
