apiVersion: virtualenvironmentfirewallalias.crossplane.io/v1alpha1
kind: EnvironmentFirewallAlias
metadata:
  name: ubuntu-firewall-alias
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: default
  forProvider:
    name: ubuntu
    cidr: 172.22.33.45
    comment: Managed by Crossplane
    nodeName: pve        
    # vmId: 100
