apiVersion: virtualenvironmentuser.crossplane.io/v1alpha1
kind: EnvironmentUser
metadata:
  name: testuser2
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  forProvider:
    userId: testuser2@pve
    firstName: Test
    lastName: User
    email: testuser2@example.com
    comment: "Managed by CrossplaneCHANGED"
    enabled: true
    passwordSecretRef:
      name: environmentuser-password
      namespace: crossplane-system
      key: password
