apiVersion: virtual.crossplane.io/v1alpha1
kind: EnvironmentClusterFirewall
metadata:
  name: example-cluster-firewall
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  forProvider:
    enabled: true
    ebtables: false
    inputPolicy: DROP
    outputPolicy: ACCEPT
    logRatelimit:
      - enabled: false
        burst: 10
        rate: "15/second"
