apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-proxmox-bpg
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers fernandomendietaovejero@gmail.com
    meta.crossplane.io/source: github.com/valkiriaaquatica/provider-proxmox-bpg
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Crossplane provider to manage Proxmox VE resources in Kubernetes
    meta.crossplane.io/readme: |
      `provider-proxmox-bpg` is the Crossplane infrastructure provider for Proxmox VE 
    friendly-name.meta.crossplane.io: Provider Proxmox BPG
