name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0
    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
      with:
        repo-token: ${{ secrets.GH_RENOVATE_WRITER_TOKEN }}