name: Generate after Renovate (commit on same PR)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

concurrency:
  group: generate-after-renovate-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-after-renovate:

    if: |
      startsWith(github.head_ref, 'renovate/') &&
      github.actor == 'renovate[bot]' &&
      (
        contains(github.event.pull_request.labels.*.name, 'proxmox') ||
        contains(github.event.pull_request.labels.*.name, 'bpg') ||
        contains(github.event.pull_request.labels.*.name, 'provider')
      ) &&
      github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    env:
      GIT_AUTHOR_NAME: "renovate-ci[bot]"
      GIT_AUTHOR_EMAIL: "renovate-ci@users.noreply.github.com"
      GIT_COMMITTER_NAME: "renovate-ci[bot]"
      GIT_COMMITTER_EMAIL: "renovate-ci@users.noreply.github.com"

    steps:
      - name: Checkout Renovate PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_RENOVATE_WRITER_TOKEN }
          fetch-depth: 0
          submodules: true

      - name: Debug
        run: |
          echo "PR branch: $GITHUB_HEAD_REF"
          echo "Actor: $GITHUB_ACTOR"
          git --no-pager log --oneline -n 5 || true
          cat Makefile || true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Tooling
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: First make generate (best-effort)
        run: |
          make generate >/dev/null 2>&1 || true

      - name: Run pre-make-generate patch
        run: |
          chmod +x ./pre-make-generate.sh
          ./pre-make-generate.sh

      - name: Second make generate (authoritative)
        run: |
          make generate

      - name: Check if changes were generated
        id: check_diff
        run: |
          if git diff --quiet; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          fi
          git status --porcelain

      - name: Commit changes back to Renovate branch
        if: steps.check_diff.outputs.no_changes == 'false'
        env:
          GH_TOKEN: ${{ secrets.GH_RENOVATE_WRITER_TOKEN }}
        run: |
          git config user.name  "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git add -A
          git commit -m "chore: regenerate after renovate bump"
          git remote set-url origin "https://${GH_TOKEN}@github.com/${{ github.repository }}.git"
          git push origin "${GITHUB_HEAD_REF}"
