name: Debug on Pull Request

on:
  pull_request: {}

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug step
        run: cat file_exist.txt
