name: Debug on Pull Request

on:
  pull_request: {}

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Debug step
        run: echo "PRunning ci"
