name: Run make generate on Renovate PR (fork-safe)

on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  regenerate:
    if: startsWith(github.event.pull_request.head.ref, 'renovate/')
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "Testing commit by GitHub Actions" > newfile.txt

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit --amend --no-edit
          git push origin HEAD --force
