name: Generate after Renovate

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  generate-after-renovate:
    if: startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Renovate PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_RENOVATE_WRITER_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "renovate-ci[bot]"
          git config user.email "renovate-ci@users.noreply.github.com"