name: Generate after Renovate

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  generate-after-renovate:
    if: startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Renovate PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_RENOVATE_WRITER_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "renovate-ci[bot]"
          git config user.email "renovate-ci@users.noreply.github.com"
      
      - name: Make a random file
        run: |
          touch random-file.txt

      - name: Create new branch and PR if needed
       #  if: steps.check_diff.outputs.no_changes == 'false'
        run: |
          NEW_BRANCH="renovate/${GITHUB_HEAD_REF#renovate/}-generated"
          git checkout -b "$NEW_BRANCH"
          git add .
          git commit -m "ci: generate files after renovate update"
          git push origin "$NEW_BRANCH"
          gh pr create \
            --base "${GITHUB_HEAD_REF}" \
            --head "$NEW_BRANCH" \
            --title "ci: generate files after renovate update" \
            --body "This pull request was auto-generated after a Renovate update to regenerate files using \`make generate\`.

          ⚠️ **Important**: This PR depends on the original Renovate PR [${GITHUB_HEAD_REF}](${{ github.event.pull_request.html_url }}).  
          It should only be merged after (or together with) the corresponding Renovate update.

          Changes were generated automatically based on the version bump of \`bpg/terraform-provider-proxmox\`.

          ---

          _This PR was created by a CI workflow to keep generated files up to date._" \
            --repo "${{ github.repository }}"


        env:
          GH_TOKEN: ${{ secrets.GH_RENOVATE_WRITER_TOKEN }}