name: Run test commit on Renovate PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  test:
    if: startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Create dummy file
        run: |
          echo "Testing commit by GitHub Actions" > newfile.txt

      - name: Commit and push dummy change
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit --amend --no-edit
          git push origin HEAD --force
