// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EntriesInitParameters struct {
}

type EntriesObservation struct {

	// The IP address.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// The hostnames.
	Hostnames []*string `json:"hostnames,omitempty" tf:"hostnames,omitempty"`
}

type EntriesParameters struct {
}

type EntryInitParameters struct {

	// The IP address.
	// The address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// The hostnames.
	// The hostnames
	Hostnames []*string `json:"hostnames,omitempty" tf:"hostnames,omitempty"`
}

type EntryObservation struct {

	// The IP address.
	// The address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// The hostnames.
	// The hostnames
	Hostnames []*string `json:"hostnames,omitempty" tf:"hostnames,omitempty"`
}

type EntryParameters struct {

	// The IP address.
	// The address
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// The hostnames.
	// The hostnames
	// +kubebuilder:validation:Optional
	Hostnames []*string `json:"hostnames" tf:"hostnames,omitempty"`
}

type EnvironmentHostsInitParameters struct {

	// A host entry (multiple blocks supported).
	// The host entries
	Entry []EntryInitParameters `json:"entry,omitempty" tf:"entry,omitempty"`

	// A node name.
	// The node name
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

type EnvironmentHostsObservation struct {

	// The IP addresses.
	// The addresses
	Addresses []*string `json:"addresses,omitempty" tf:"addresses,omitempty"`

	// The SHA1 digest.
	// The SHA1 digest
	Digest *string `json:"digest,omitempty" tf:"digest,omitempty"`

	// The host entries (conversion of addresses and hostnames into
	// objects).
	// The host entries
	Entries []EntriesObservation `json:"entries,omitempty" tf:"entries,omitempty"`

	// A host entry (multiple blocks supported).
	// The host entries
	Entry []EntryObservation `json:"entry,omitempty" tf:"entry,omitempty"`

	// The hostnames.
	// The hostnames
	Hostnames [][]*string `json:"hostnames,omitempty" tf:"hostnames,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A node name.
	// The node name
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

type EnvironmentHostsParameters struct {

	// A host entry (multiple blocks supported).
	// The host entries
	// +kubebuilder:validation:Optional
	Entry []EntryParameters `json:"entry,omitempty" tf:"entry,omitempty"`

	// A node name.
	// The node name
	// +kubebuilder:validation:Optional
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

// EnvironmentHostsSpec defines the desired state of EnvironmentHosts
type EnvironmentHostsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EnvironmentHostsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EnvironmentHostsInitParameters `json:"initProvider,omitempty"`
}

// EnvironmentHostsStatus defines the observed state of EnvironmentHosts.
type EnvironmentHostsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EnvironmentHostsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EnvironmentHosts is the Schema for the EnvironmentHostss API. |  Manages the host entries on a specific node.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,proxmoxbpg}
type EnvironmentHosts struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entry) || (has(self.initProvider) && has(self.initProvider.entry))",message="spec.forProvider.entry is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nodeName) || (has(self.initProvider) && has(self.initProvider.nodeName))",message="spec.forProvider.nodeName is a required parameter"
	Spec   EnvironmentHostsSpec   `json:"spec"`
	Status EnvironmentHostsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EnvironmentHostsList contains a list of EnvironmentHostss
type EnvironmentHostsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EnvironmentHosts `json:"items"`
}

// Repository type metadata.
var (
	EnvironmentHosts_Kind             = "EnvironmentHosts"
	EnvironmentHosts_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EnvironmentHosts_Kind}.String()
	EnvironmentHosts_KindAPIVersion   = EnvironmentHosts_Kind + "." + CRDGroupVersion.String()
	EnvironmentHosts_GroupVersionKind = CRDGroupVersion.WithKind(EnvironmentHosts_Kind)
)

func init() {
	SchemeBuilder.Register(&EnvironmentHosts{}, &EnvironmentHostsList{})
}
